apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deployment
spec:
  selector:
    matchLabels:
      app: react-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend-container
          image: public.ecr.aws/a7h7p8n1/react-frontend:1.0
          ports:
            - containerPort: 5173